Encoding:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

DoubleNegation:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Enabled: false

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "Guardfile"
    - "config/unicorn.rb"
